import emailHintRequester from './emailHintRequester';
import {
  POSTAL_CODE,
  REGION_CODE,
  AREA,
  CITY,
  SETTLEMENT,
  STREET,
  HOUSE,
  BLOCK,
  FULL_ADDRESS,
  addressHintRequester,
} from './addressHintRequester';

export {
  emailHintRequester,

  POSTAL_CODE as ADDRESS_HINT_REQUESTER_POSTAL_CODE,
  REGION_CODE as ADDRESS_HINT_REQUESTER_REGION_CODE,
  AREA as ADDRESS_HINT_REQUESTER_AREA,
  CITY as ADDRESS_HINT_REQUESTER_CITY,
  SETTLEMENT as ADDRESS_HINT_REQUESTER_SETTLEMENT,
  STREET as ADDRESS_HINT_REQUESTER_STREET,
  HOUSE as ADDRESS_HINT_REQUESTER_HOUSE,
  BLOCK as ADDRESS_HINT_REQUESTER_BLOCK,
  FULL_ADDRESS as ADDRESS_HINT_REQUESTER_FULL,
  addressHintRequester,
  
};
