import HintedEmailInput from './components/HintedEmailInput';
import HintedAddressInput from './components/HintedAddressInput';

import {
  ADDRESS_HINT_REQUESTER_POSTAL_CODE,
  ADDRESS_HINT_REQUESTER_REGION_CODE,
  ADDRESS_HINT_REQUESTER_AREA,
  ADDRESS_HINT_REQUESTER_CITY,
  ADDRESS_HINT_REQUESTER_SETTLEMENT,
  ADDRESS_HINT_REQUESTER_STREET,
  ADDRESS_HINT_REQUESTER_HOUSE,
  ADDRESS_HINT_REQUESTER_BLOCK,
  ADDRESS_HINT_REQUESTER_FULL,
} from './components/api/index';

export {
  HintedEmailInput,

  HintedAddressInput,
  ADDRESS_HINT_REQUESTER_POSTAL_CODE,
  ADDRESS_HINT_REQUESTER_REGION_CODE,
  ADDRESS_HINT_REQUESTER_AREA,
  ADDRESS_HINT_REQUESTER_CITY,
  ADDRESS_HINT_REQUESTER_SETTLEMENT,
  ADDRESS_HINT_REQUESTER_STREET,
  ADDRESS_HINT_REQUESTER_HOUSE,
  ADDRESS_HINT_REQUESTER_BLOCK,
  ADDRESS_HINT_REQUESTER_FULL,
 };
